inputs:
  to:
    description: "Telegram channel id"
  token:
    description: "Telegram chatbot token"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
      with:
        repository: bravo680git/tele-notify
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - shell: bash
      run: |
          echo "TOKEN=${{ inputs.token }}" >> .env
          echo "TO=${{ inputs.to }}" >> .env
          echo "BRANCH=${{ github.ref_name }}" >> .env
          echo "JOB_NAME=${{ github.job }}" >> .env
          echo "REPO=${{ github.repository }}" >> .env
          echo "RUN_ID=${{ github.run_id }}" >> .env
          echo "STATUS=${{ job.status }}" >> .env
          echo "WF_NAME=${{ github.workflow }}" >> .env
          
          node --env-file=.env index.mjs
