inputs:
  status:
    description: "Job status (success or failure)"
    required: true
  project:
    description: "Project name and stage"
  to:
    description: "Telegram channel id"
  token:
    description: "Telegram chatbot token"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - shell: bash
      run: |
          echo "TOKEN=${{ inputs.token }}" >> .env
          echo "TO=${{ inputs.to }}" >> .env
          node --env-file=.env index.js
